Repository sparta-java-team-30/backend, pull requests merged in 2025-02, with the labels that each got.

#2 chore(configuration): 데이터 베이스 설정 (#1)
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: configuration

#7 feat(user): 회원 엔티티 생성 (#5)
  src/main/java/com/sparta/team30/user/domain/User.java
Labels: feature

#8 Revert "feat(user): 회원 엔티티 생성 (#5)"
  src/main/java/com/sparta/team30/user/domain/User.java
Labels: refactor

#10 refactor(user): 회원 엔티티 수정 (#9)
  src/main/java/com/sparta/team30/user/domain/User.java
Labels: feature, refactor

#28 Feat(review)/review create : 공통엔티티/리뷰엔티티 추가
  src/main/java/com/sparta/team30/Team30Application.java
  src/main/java/com/sparta/team30/common/domain/BaseEntity.java
  src/main/java/com/sparta/team30/review/domain/review.java
Labels: feature

#32 feat: 장바구니 엔티티 생성 (#20)
  src/main/java/com/sparta/team30/carts/domain/Cart.java
Labels: feature

#34 feat(user): 라이브러리 추가 및 설정 (#33)
  build.gradle
  src/main/java/com/sparta/team30/infrastructure/config/WebSecurityConfig.java
Labels: feature

#40 chore(configuration): QueryDSL Configuration (#21)
  src/main/java/com/sparta/team30/infrastructure/config/QueryDslConfig.java
Labels: configuration

#44 refactor(store): deprecated된 annotation 변경과 JPA Auditing 적용 (#27)
  src/main/java/com/sparta/team30/store/domain/Store.java
Labels: refactor

#46 refactor(category): deprecated된 annotation 변경과 JPA Auditing 적용 (#45)
  src/main/java/com/sparta/team30/category/domain/Category.java
Labels: refactor

#50 chore(configuration): GlobalException 구현 (#49)
  src/main/java/com/sparta/team30/common/exception/ErrorResponse.java
  src/main/java/com/sparta/team30/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/team30/common/exception/UserEmailAlreadyExistsException.java
  src/main/java/com/sparta/team30/common/exception/UserPasswordIncorrectException.java
  src/main/java/com/sparta/team30/common/exception/UsernameAlreadyExistsException.java
Labels: configuration

#56 chore(configuration): Spring Validation 의존성 추가 (#21)
  build.gradle
Labels: configuration

#54 feat(user): User Signup 구현 (#33)
  src/main/java/com/sparta/team30/infrastructure/security/UserDetailsImpl.java
  src/main/java/com/sparta/team30/infrastructure/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/team30/user/dto/UserSignUpRequestDto.java
  src/main/java/com/sparta/team30/user/repository/UserRepository.java
  src/main/java/com/sparta/team30/user/repository/UserRepositoryCustom.java
  src/main/java/com/sparta/team30/user/repository/UserRepositoryImpl.java
  src/main/java/com/sparta/team30/user/service/UserService.java
  src/main/java/com/sparta/team30/user/service/UserServiceImpl.java
Labels: feature

#51 feat: 주문하기 기능 추가 (#37)
  src/main/java/com/sparta/team30/order/controlller/OrderController.java
  src/main/java/com/sparta/team30/order/domain/Order.java
  src/main/java/com/sparta/team30/order/domain/OrderDetail.java
  src/main/java/com/sparta/team30/order/dto/RequestCreateOrderDTO.java
  src/main/java/com/sparta/team30/order/dto/RequestOrderProductDTO.java
  src/main/java/com/sparta/team30/order/dto/ResponseCreateOrderDTO.java
  src/main/java/com/sparta/team30/order/repository/OrderDetailRepository.java
  src/main/java/com/sparta/team30/order/repository/OrderRepository.java
  src/main/java/com/sparta/team30/order/service/OrderDetailService.java
  src/main/java/com/sparta/team30/order/service/OrderService.java
  src/main/java/com/sparta/team30/payment/domain/Payment.java
  src/main/java/com/sparta/team30/products/repository/ProductRepository.java
  src/test/java/com/sparta/team30/order/service/OrderServiceTest.java
Labels: feature

#68 feat(category): 카테고리 조회 기능 구현 (#66)
  src/main/java/com/sparta/team30/category/controller/CategoryController.java
  src/main/java/com/sparta/team30/category/dto/CategoryResponseDto.java
  src/main/java/com/sparta/team30/category/respository/CategoryRepository.java
  src/main/java/com/sparta/team30/category/service/CategoryService.java
Labels: feature

#69 feat(category): 카테고리 생성 기능 구현 (#66)
  http/Category.http
  src/main/java/com/sparta/team30/category/controller/CategoryController.java
  src/main/java/com/sparta/team30/category/domain/Category.java
  src/main/java/com/sparta/team30/category/dto/CategoryRequestDto.java
  src/main/java/com/sparta/team30/category/service/CategoryService.java
Labels: feature

#70 feat(category): 카테고리 수정 기능 구현 (#66)
  src/main/java/com/sparta/team30/category/controller/CategoryController.java
  src/main/java/com/sparta/team30/category/domain/Category.java
  src/main/java/com/sparta/team30/category/service/CategoryService.java
  src/main/java/com/sparta/team30/common/exception/CategoryNotFoundException.java
  src/main/java/com/sparta/team30/common/exception/GlobalExceptionHandler.java
Labels: feature

#71 feat(category): 카테고리 삭제 기능 구현 (#66)
  src/main/java/com/sparta/team30/category/controller/CategoryController.java
  src/main/java/com/sparta/team30/category/domain/Category.java
  src/main/java/com/sparta/team30/category/service/CategoryService.java
  src/main/java/com/sparta/team30/common/domain/BaseEntity.java
Labels: feature

#75 refactor(store): Store 엔티티 수정 (#73)
  src/main/java/com/sparta/team30/store/domain/Store.java
Labels: refactor

#76 feat(user): JWT 구현 (#60)
  src/main/java/com/sparta/team30/common/util/JwtProperties.java
  src/main/java/com/sparta/team30/common/util/TokenProvider.java
  src/main/java/com/sparta/team30/infrastructure/config/SwaggerConfig.java
  src/main/java/com/sparta/team30/infrastructure/config/WebSecurityConfig.java
  src/main/java/com/sparta/team30/infrastructure/security/TokenAuthenticationFilter.java
  src/main/java/com/sparta/team30/infrastructure/security/TokenGenerateFilter.java
  src/main/java/com/sparta/team30/infrastructure/security/UserDetailsImpl.java
  src/main/resources/application.yml
Labels: feature

#77 feat(user): 회원 로그인 API 구현 (#60)
  http/User.http
  src/main/java/com/sparta/team30/user/controller/UserController.java
  src/main/java/com/sparta/team30/user/dto/UserSignInRequestDto.java
Labels: feature

#83 feat(user): 회원 정보 수정 구현 (#82)
  src/main/java/com/sparta/team30/common/util/TokenProvider.java
  src/main/java/com/sparta/team30/infrastructure/config/WebSecurityConfig.java
  src/main/java/com/sparta/team30/infrastructure/security/TokenAuthenticationFilter.java
  src/main/java/com/sparta/team30/user/controller/UserController.java
  src/main/java/com/sparta/team30/user/domain/User.java
  src/main/java/com/sparta/team30/user/dto/UserInfoUpdateRequestDto.java
  src/main/java/com/sparta/team30/user/service/UserService.java
  src/main/java/com/sparta/team30/user/service/UserServiceImpl.java
Labels: feature

#85 feat(user): 회원 탈퇴 구현 (#84)
  http/User.http
  src/main/java/com/sparta/team30/user/controller/UserController.java
  src/main/java/com/sparta/team30/user/domain/User.java
  src/main/java/com/sparta/team30/user/dto/UserDeleteRequestDto.java
  src/main/java/com/sparta/team30/user/dto/UserInfoUpdateRequestDto.java
  src/main/java/com/sparta/team30/user/service/UserService.java
  src/main/java/com/sparta/team30/user/service/UserServiceImpl.java
Labels: feature

#103 feat(product): 상품 설명 기능 구현 (#102)
  src/main/java/com/sparta/team30/infrastructure/config/RestClientConfig.java
  src/main/java/com/sparta/team30/products/controller/ProductDetailController.java
  src/main/java/com/sparta/team30/products/controller/ProductDetailHistoryController.java
  src/main/java/com/sparta/team30/products/domain/ProductDetail.java
  src/main/java/com/sparta/team30/products/domain/ProductDetailHistory.java
  src/main/java/com/sparta/team30/products/dto/ProductDetailHistoryRequestDto.java
  src/main/java/com/sparta/team30/products/dto/ProductDetailHistoryResponseDto.java
  src/main/java/com/sparta/team30/products/dto/ProductDetailRequestDto.java
  src/main/java/com/sparta/team30/products/dto/ProductDetailResponseDto.java
  src/main/java/com/sparta/team30/products/repository/ProductDetailHistoryRepository.java
  src/main/java/com/sparta/team30/products/repository/ProductDetailHistoryRepositoryCustom.java
  src/main/java/com/sparta/team30/products/repository/ProductDetailHistoryRepositoryImpl.java
  src/main/java/com/sparta/team30/products/repository/ProductDetailRepository.java
  src/main/java/com/sparta/team30/products/repository/ProductDetailRepositoryCustom.java
  src/main/java/com/sparta/team30/products/repository/ProductDetailRepositoryImpl.java
  src/main/java/com/sparta/team30/products/service/ProductDetailHistoryService.java
  src/main/java/com/sparta/team30/products/service/ProductDetailHistoryServiceImpl.java
  src/main/java/com/sparta/team30/products/service/ProductDetailService.java
  src/main/java/com/sparta/team30/products/service/ProductDetailServiceImpl.java
  src/main/resources/application.yml
Labels: feature

#104 Refactor: 장바구니 기능 수정 (#101)
  src/main/java/com/sparta/team30/carts/controller/CartController.java
  src/main/java/com/sparta/team30/carts/domain/Cart.java
  src/main/java/com/sparta/team30/carts/domain/CartItem.java
  src/main/java/com/sparta/team30/carts/dto/CartItemRequestDto.java
  src/main/java/com/sparta/team30/carts/dto/CartItemResponseDto.java
  src/main/java/com/sparta/team30/carts/dto/CartRequestDto.java
  src/main/java/com/sparta/team30/carts/dto/CartResponseDto.java
  src/main/java/com/sparta/team30/carts/repository/CartRepository.java
  src/main/java/com/sparta/team30/carts/service/CartService.java
Labels: refactor

#105 feat: 결제 조회, 취소 권한 추가 (#98)
  http/Address.http
  src/main/java/com/sparta/team30/address/controller/AddressController.java
  src/main/java/com/sparta/team30/address/domain/Address.java
  src/main/java/com/sparta/team30/address/dto/ResponseAddressDTO.java
  src/main/java/com/sparta/team30/address/dto/ResponseAddressDetailsDTO.java
  src/main/java/com/sparta/team30/address/repository/AddressRepository.java
  src/main/java/com/sparta/team30/address/repository/AddressRepositoryCustom.java
  src/main/java/com/sparta/team30/address/repository/AddressRepositoryImpl.java
  src/main/java/com/sparta/team30/address/service/AddressService.java
  src/main/java/com/sparta/team30/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/team30/common/exception/PaymentNotFoundException.java
  src/main/java/com/sparta/team30/order/domain/Order.java
  src/main/java/com/sparta/team30/order/dto/ResponseOrderDetailsDTO.java
  src/main/java/com/sparta/team30/order/service/OrderService.java
  src/main/java/com/sparta/team30/payment/controller/PaymentController.java
  src/main/java/com/sparta/team30/payment/domain/Payment.java
  src/main/java/com/sparta/team30/payment/dto/ResponsePaymentDetailDTO.java
  src/main/java/com/sparta/team30/payment/dto/ResponsePaymentHistoryDTO.java
  src/main/java/com/sparta/team30/payment/repository/PaymentRepository.java
  src/main/java/com/sparta/team30/payment/service/PaymentService.java
Labels: feature

#106 feat(store): 음식점 기능 구현 (#97)
  src/main/java/com/sparta/team30/common/exception/DuplicateStoreException.java
  src/main/java/com/sparta/team30/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/team30/common/exception/StoreNotFoundException.java
  src/main/java/com/sparta/team30/store/controller/StoreController.java
  src/main/java/com/sparta/team30/store/domain/Store.java
  src/main/java/com/sparta/team30/store/dto/StoreApproveResponseDto.java
  src/main/java/com/sparta/team30/store/dto/StoreCreateResponseDto.java
  src/main/java/com/sparta/team30/store/dto/StoreDeleteResponseDto.java
  src/main/java/com/sparta/team30/store/dto/StoreListResponseDto.java
  src/main/java/com/sparta/team30/store/dto/StoreRequestDto.java
  src/main/java/com/sparta/team30/store/dto/StoreResponseDto.java
  src/main/java/com/sparta/team30/store/dto/StoreUpdateRequestDto.java
  src/main/java/com/sparta/team30/store/repository/StoreRepository.java
  src/main/java/com/sparta/team30/store/repository/StoreRepositoryCustom.java
  src/main/java/com/sparta/team30/store/repository/StoreRepositoryImpl.java
  src/main/java/com/sparta/team30/store/service/StoreService.java
Labels: feature

#120 feat(user): 회원 권한 변경 기능 구현 (#119)
  http/User.http
  src/main/java/com/sparta/team30/common/config/JpaConfig.java
  src/main/java/com/sparta/team30/common/config/QueryDslConfig.java
  src/main/java/com/sparta/team30/common/config/RestClientConfig.java
  src/main/java/com/sparta/team30/common/config/SwaggerConfig.java
  src/main/java/com/sparta/team30/common/config/WebSecurityConfig.java
  src/main/java/com/sparta/team30/common/security/TokenAuthenticationFilter.java
  src/main/java/com/sparta/team30/common/security/TokenGenerateFilter.java
  src/main/java/com/sparta/team30/common/security/UserDetailsImpl.java
  src/main/java/com/sparta/team30/common/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/team30/order/controlller/OrderController.java
  src/main/java/com/sparta/team30/review/controller/ReviewController.java
  src/main/java/com/sparta/team30/user/controller/UserController.java
  src/main/java/com/sparta/team30/user/domain/User.java
  src/main/java/com/sparta/team30/user/domain/UserRoleEnum.java
  src/main/java/com/sparta/team30/user/dto/UserInfoResponse.java
  src/main/java/com/sparta/team30/user/dto/UserRoleUpdateManagerRequest.java
  src/main/java/com/sparta/team30/user/dto/UserRoleUpdateMasterRequest.java
  src/main/java/com/sparta/team30/user/dto/UserRoleUpdateOwnerRequest.java
  src/main/java/com/sparta/team30/user/service/UserService.java
  src/main/java/com/sparta/team30/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: feature

#122 refactor(product): 상품 설명 외부 API 분리 (#121)
  src/main/java/com/sparta/team30/common/external/ExternalApiService.java
  src/main/java/com/sparta/team30/common/external/dto/ExternalApiRequestDto.java
  src/main/java/com/sparta/team30/common/external/dto/ExternalApiResponseDto.java
  src/main/java/com/sparta/team30/products/controller/ProductDetailController.java
  src/main/java/com/sparta/team30/products/controller/ProductDetailHistoryController.java
  src/main/java/com/sparta/team30/products/dto/ProductDetailHistoryResponseDto.java
  src/main/java/com/sparta/team30/products/service/ProductDetailHistoryService.java
  src/main/java/com/sparta/team30/products/service/ProductDetailHistoryServiceImpl.java
  src/main/java/com/sparta/team30/products/service/ProductDetailService.java
  src/main/java/com/sparta/team30/products/service/ProductDetailServiceImpl.java
Labels: refactor

#131 feat: 배송지, 결제 테스트 추가 (#126)
  src/main/java/com/sparta/team30/address/controller/AddressController.java
  src/main/java/com/sparta/team30/address/domain/Address.java
  src/main/java/com/sparta/team30/address/dto/RequestUpdateAddressDTO.java
  src/main/java/com/sparta/team30/address/service/AddressService.java
  src/main/java/com/sparta/team30/order/controlller/OrderController.java
  src/main/java/com/sparta/team30/order/dto/RequestCreateOrderDTO.java
  src/main/java/com/sparta/team30/order/dto/RequestUpdateOrderDTO.java
  src/main/java/com/sparta/team30/order/dto/ResponseCreateOrderDTO.java
  src/main/java/com/sparta/team30/order/repository/OrderDetailRepositoryCustom.java
  src/main/java/com/sparta/team30/order/repository/OrderDetailRepositoryImpl.java
  src/main/java/com/sparta/team30/order/repository/OrderRepository.java
  src/main/java/com/sparta/team30/order/repository/OrderRepositoryCustom.java
  src/main/java/com/sparta/team30/order/service/OrderService.java
  src/main/java/com/sparta/team30/payment/domain/Payment.java
  src/main/java/com/sparta/team30/payment/dto/RequestPaymentByOrderId.java
  src/main/java/com/sparta/team30/payment/service/PaymentService.java
  src/test/java/com/sparta/team30/address/service/AddressServiceTest.java
  src/test/java/com/sparta/team30/order/service/OrderServiceTest.java
  src/test/java/com/sparta/team30/payment/service/PaymentServiceTest.java
Labels: feature

#132 refactor(category): Category 기능 수정 (#73)
  http/Store.http
  src/main/java/com/sparta/team30/category/domain/Category.java
  src/main/java/com/sparta/team30/category/dto/CategoryDto.java
  src/main/java/com/sparta/team30/category/service/CategoryService.java
  src/main/java/com/sparta/team30/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/team30/store/controller/StoreController.java
  src/main/java/com/sparta/team30/store/domain/Store.java
  src/main/java/com/sparta/team30/store/exception/NotStoreOwnerException.java
  src/main/java/com/sparta/team30/store/exception/StoreAlreadyApproveException.java
  src/main/java/com/sparta/team30/store/exception/StoreAlreadyDeleteException.java
  src/main/java/com/sparta/team30/store/exception/StoreNotApproveException.java
  src/main/java/com/sparta/team30/store/exception/StoreOwnerAlreadyExistsException.java
  src/main/java/com/sparta/team30/store/exception/StoreUpdateFailException.java
  src/main/java/com/sparta/team30/store/exception/UserHasNoStoreException.java
  src/main/java/com/sparta/team30/store/repository/StoreRepositoryCustom.java
  src/main/java/com/sparta/team30/store/repository/StoreRepositoryImpl.java
  src/main/java/com/sparta/team30/store/service/StoreService.java
Labels: refactor

#134 feat(store): 내 음식점 관련 주문 조회 (#133)
  src/main/java/com/sparta/team30/order/dto/ResponseMyStoreOrderListDTO.java
  src/main/java/com/sparta/team30/order/repository/OrderDetailRepositoryCustom.java
  src/main/java/com/sparta/team30/order/repository/OrderDetailRepositoryImpl.java
  src/main/java/com/sparta/team30/order/service/OrderDetailService.java
  src/main/java/com/sparta/team30/store/controller/StoreController.java
  src/main/java/com/sparta/team30/store/dto/StoreRequestDto.java
  src/main/java/com/sparta/team30/store/dto/StoreResponseDto.java
  src/main/java/com/sparta/team30/user/dto/UserDto.java
Labels: feature

#138 feat(store): 내 음식점 관련 결제 조회 (#133)
  src/main/java/com/sparta/team30/order/dto/ResponseMyStoreOrderListDTO.java
  src/main/java/com/sparta/team30/order/repository/OrderDetailRepositoryImpl.java
  src/main/java/com/sparta/team30/payment/dto/PaymentDTO.java
  src/main/java/com/sparta/team30/store/controller/StoreController.java
  src/main/java/com/sparta/team30/store/dto/StoreRequestDto.java
Labels: feature

#142 refactor(category): 카테고리 기능 수정 (#107)
  src/main/java/com/sparta/team30/category/domain/Category.java
  src/main/java/com/sparta/team30/category/dto/CategoryRequestDto.java
  src/main/java/com/sparta/team30/category/respository/CategoryRepositoryImpl.java
Labels: refactor

#150 configuration : Github CI/CD (#149)
  .github/workflows/cicd.yml
  Dockerfile
  src/main/resources/application-prod.yml
Labels: configuration

#161 feat(store): 음식점 테스트 코드 작성 (#156)
  src/main/java/com/sparta/team30/store/dto/StoreRequestDto.java
  src/test/java/com/sparta/team30/store/service/StoreServiceTest.java
Labels: feature
